name: mvp
description: A playground for experimenting with multiple views.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-378.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  sky_engine:
    path: /Users/tongmu/dev/engine/src/out/host_debug_unopt/gen/dart-pkg/sky_engine
